"""Canvas Wire Protocol v1 — the typed contract shared with the frontend."""

from .artifacts import (
    Artifact,
    ArtifactData,
    ArtifactStatus,
    ChartData,
    ChartOptions,
    ChartSeries,
    DocumentData,
    FileData,
    HtmlData,
    TableColumn,
    TableData,
)
from .events import (
    CanvasAppend,
    CanvasCommit,
    CanvasCreate,
    CanvasEvent,
    CanvasNodePatch,
    CanvasPatch,
    CanvasReplace,
    CanvasStatus,
    DoneEvent,
    ErrorEvent,
    MessageDelta,
    MessageEnd,
    StreamEvent,
    ToolEnd,
    ToolStart,
)

__all__ = [
    # artifacts
    "Artifact",
    "ArtifactData",
    "ArtifactStatus",
    "HtmlData",
    "DocumentData",
    "FileData",
    "ChartData",
    "ChartSeries",
    "ChartOptions",
    "TableColumn",
    "TableData",
    # events
    "MessageDelta",
    "MessageEnd",
    "ToolStart",
    "ToolEnd",
    "CanvasCreate",
    "CanvasAppend",
    "CanvasPatch",
    "CanvasNodePatch",
    "CanvasReplace",
    "CanvasStatus",
    "CanvasCommit",
    "ErrorEvent",
    "DoneEvent",
    "CanvasEvent",
    "StreamEvent",
]
